username: Kevin Wu
typing_text: Student at William and Mary
email: kwu06@email.wm.edu
github_username: kevinypw
show_aboutme_card: true
about_me_title: About Me
about_me_description: Hey, I am a student at William and Mary, and I am taking DATA100 - Wicked Problems as of Spring 2021. I went to high school at TJHSST, and am from Northern Virginia.
show_timeline_card: false
show_projects: true
show_projects_card: true
show_informals: true
show_informal_card: true
projects_title: Projects
informals_title: Informal Responses
show_contact_card: false
title: Kevin Wu's Data100 Site