# .github/workflows/build-and-deploy.yml

name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Update package-lock.json
        run: |
          cd reactWebsite
          rm package-lock.json
          npm install

      - uses: actions/setup-node@v3
        with:
          # update the Node version to meet your needs
          node-version: 18
          cache: npm
          cache-dependency-path: './reactWebsite/package-lock.json'

      - name: Build
        working-directory: reactWebsite
        run: |
          npm ci
          npm run build
          touch out/.nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: main
          folder: reactWebsite/out
